### ISSUE TITLE
Filesystem errors (tempfs)

### ISSUE THREAD

**Issue by bedawi** [flathub/im.riot.Riot#108]
Hi there.

I am not certain that this is the right place to report this error. If it's not caused by the flathub-specific version please forward the bug report or let me know where I shall place it.

### Environment

Fedora 32, Kerel 5.6.14-300.fc32.x86_64
Gnome Desktop
Flathub / Flatpak

### Error

When Riot starts the folder ```/run/user/1000/doc/``` is being created. It seems to have wrong properties.

### Details

```bash
tree /run/user/1000/doc
/run/user/1000/doc
└── by-app
    └── im.riot.Riot

ls -alZ /run/user/1000/doc/
insgesamt 0
dr-x------.  2 username usergroup system_u:object_r:fusefs_t:s0     0  1. Jan 1970  .
drwx------. 17 username usergroup system_u:object_r:user_tmp_t:s0 440 28. Mai 22:21 ..
dr-x------.  2 username usergroup system_u:object_r:fusefs_t:s0     0  1. Jan 1970  by-app
```

The folders have some weird properties and other programs (like df) throw error messages:

```bash
df -h
df: /run/user/1000/doc: Die Operation ist nicht erlaubt
Dateisystem                             Größe Benutzt Verf. Verw% Eingehängt auf
--lines removed--
tmpfs                                    1,6G     20M  1,6G    2% /run/user/1000
```

Translation: operation not permitted.

These folders are not removed after the Riot application is being closed. They cannot be modified (not even with root privileges). 

Greetings
Ben

**Comment by Erick555** [comment]
`/run/user/1000/doc/` is `fuse` filesystem not `tmpfs`. It's used by flatpak for accessing files through portal although riot (electron) doesn't use portals yet. Everything is ok here.

**Comment by SISheogorath** [comment]
I think if any further discussion of this is needed, https://github.com/flatpak/flatpak is the better place for it :)
