### ISSUE TITLE
Prepare for name change

### ISSUE THREAD

**Issue by SISheogorath** [flathub/im.riot.Riot#114]
[Riot has announced](https://blog.riot.im/the-world-is-changing/) that it'll change it's name soon.

Looking at how those things are handled in other flatpaks I think it means we need to prepare a EOL tag as well as a new repository to continue our work.

@barthalion can you look into this? I'm not part of the flathub organisation and also don't know the exact workflow here.

**Comment by SISheogorath** [comment]
The new name was now published: Element. I guess we need a new repository `io.element.Element`? Should this go through the regular applying process or do we have a shortcut?

**Comment by alatiera** [comment]
Until the application upstream changes the app id, I don't see any point on doing it. Android and ios still use the old id app pages as well.

**Comment by SISheogorath** [comment]
After talking to the devs as I noticed that the app-id didn't change even after the update, turns out they don't want to change the app-id.

Sounds fine if we stick with it then as well. I mean, less work for us.

https://github.com/vector-im/riot-desktop/blob/71c8ea417d033a3470e73d3658eaa8d246539d24/package.json#L65

**Comment by Erick555** [comment]
Hm, shouldn't flatpak name be `im.riot.app` then?

Anyway I can imagine users confusion when they have to use `flatpak install im.riot.Riot` long time after that name perishes from common knowledge.

**Comment by SISheogorath** [comment]
Yeah, that's my concern as well. I wonder what the flathub policy is for those cases. Any examples on how this should be handled?

I'll leave it to everyone whether or not I supply 1.7.0 as new flatpak or in this repository. I'm too undecided on it.

**Comment by barthalion** [comment]
I think we were too relaxed about app ID renames in the past. User experience around it is wonky or simply non-existent; unless application is being maintained by upstream developers or current ID causes actual issues (like it was with the old OSS build of VSCode), I don't see a reason to do it.

**Comment by SISheogorath** [comment]
I prepared a PR, if there is no big backlash by tomorrow (2020-07-16 ~12:00 UTC), I'll merge it.

**Comment by heipa0** [comment]
I would naturally expect the config files for the app in `~/.var/app/io.element.Element` and the way to install it `flatpak install flathub io.element.Elemet`

If I wouldn't know about the rebranding I would find an application ID which is totally different from the app name very confusing.

Also one reason for the name change was that Riot can be misunderstood as violence. So imho it would be better to get totally rid of this name.

However, as there is already a PR I guess it’s already decided to keep to old repo name.

**Comment by alatiera** [comment]
> If I wouldn't know about the rebranding I would find an application ID which is totally different from the app name very confusing.

app-ids are not visible in User Interfaces, the appdata should be enough for you to find `Element` searching at any store frontend.

**Comment by heipa0** [comment]
The app ID is visible. For example in the flathub url: `https://flathub.org/apps/details/im.riot.Riot `
Or in the installation instructions: 
![riot](https://user-images.githubusercontent.com/35292661/87623640-71e36980-c758-11ea-853b-4a5b99567046.png)

**Comment by SISheogorath** [comment]
> However, as there is already a PR I guess it’s already decided to keep to old repo name.

I created it to get things moving, not to take a decision away. It would be little helpful to no update at all. We might even merge it and change the app ID afterwards. But I don't want to fall behind the upstream versions.

**Comment by martijnkruiten** [comment]
I agree with not falling behind the upstream versions, the ID can be changed later. The app itself is still named "Element (Riot.im)" on other platforms, so it's clearly in a transitional phase.

Is it possible to change the ID without breaking the update functionality?

**Comment by cwmke** [comment]
I believe they left "Riot" in some spaces [to attempt to avoid confusion](https://element.io/blog/welcome-to-element/). At some point in the future I imagine they will move the Github repos and update the naming elsewhere such as mentioned here.

"To aid the transition, we’ve named the installable apps “Element (Riot.im)” for a while to help people get reoriented (e.g. when searching by name for Riot)."

**Comment by foresto** [comment]
As a user, I find it important that the flatpak ID match the app name. It *is* visible in the user interface, and is also the way I find related information like the source code and issue tracker.

Perhaps just as importantly, apps published with IDs that don't match their names set off my internal security alarm, making me suspicious that they might be malware. Even if the discrepancy is explained, I tend to be uncomfortable installing them.

+1 for migrating to a new ID soon, but it can probably wait a little while, to avoid blocking the current release and to give existing users time to get familiar with the new name & branding.

**Comment by SISheogorath** [comment]
There are currently no intends to change the app ID anymore.
