### ISSUE TITLE
Element can not be pinned to KDE task manager or Latte-Dock

### ISSUE THREAD

**Issue by chrisHRD** [flathub/im.riot.Riot#121]
Previously with Riot.im (prior to the Element name change), my office desktops could pin the flatpak launcher to Plasma's icon-only taskbar or the dock (latte-dock). However since the rebrand, the app is no longer pinnable. With some trickiery, I pinned something on the dock, but when clicked a new instance of the icon is spawned. ~~Maybe this is similar to #116 ?~~

- Operating System: Fedora 32
- KDE Plasma Version: 5.18.5
- KDE Frameworks Version: 5.70.0
- Qt Version: 5.14.2
- Kernel Version: 5.7.8-200.fc32.x86_64
- OS Type: 64-bit
- Processors: 4 × Intel® Core™ i5-4690K CPU @ 3.50GHz
- Memory: 15.5 GiB of RAM
- Flatpak: Element, im.riot.Riot, 1.7.1, stable, flathub, system

![dual-instance-no-pin](https://user-images.githubusercontent.com/32101046/87953847-2ccd7900-ca71-11ea-98ba-fc8197eddf63.png)

**Comment by Erick555** [comment]
The other issue is about ancient flatpak so unrelated to this one.

**Comment by SISheogorath** [comment]
@chrisHRD Can you check if the testbuild from #126 fixes the problem?

**Comment by chrisHRD** [comment]
@SISheogorath Just ran a quick test. 
- Pinning icon to the Plasma taskbar now works.
- Closing an open Element window (with app still running in tray), the icon now properly remains on the taskbar if pinned.
- Tested on a second machine with latte-dock, pinning now works.

Looks goods on my end.
