### ISSUE TITLE
Searching for "matrix" on flathub or flatpak does not return Element

### ISSUE THREAD

**Issue by choffee** [flathub/im.riot.Riot#138]
Hi,
I don't know if its a simple as adding "matrix client" into the description but when you search for matrix on either flathub or local repositories it does not show this client. Given the recent name change it might help with discovery.

Maybe adding "(formally Riot)" would also clear things up after the name change. Although searching for riot does work.

Thanks

**Comment by SISheogorath** [comment]
Excellent idea, we should add some `keywords` to the desktop file 👍 

Any recommendations besides `matrix` and `riot`?

**Comment by choffee** [comment]
I think those are the two for this one as a minimum.

Might also want to add "chat" "social". Not sure where you would add them, maybe the .desktop file?

There is a section on renaming applications in the AppData Guidelines, that may offer some help.
https://github.com/flathub/flathub/wiki/AppData-Guidelines

**Comment by wjt** [comment]
You add them to the `.desktop` file, and they are merged into the appstream file for Flathub at build time.
