### ISSUE TITLE
As a multimedia messenger, Element should allow sending files using the system file picker

### ISSUE THREAD

**Issue by Follpvosten** [flathub/im.riot.Riot#143]
At the moment, the flatpak build can, by default, not access any files; the open file dialog looks like this for me:
![Screenshot](https://user-images.githubusercontent.com/22855787/97274780-69113200-1835-11eb-9566-390b94f8f7db.png)
I can locally fix this by passing e.g. `--filesystem=home` to a `flatpak run` command, but I don't think this should be opt-in, so I'd propose a patch to im.riot.Riot.json adding at least `--filesystem=xdg-pictures`, `--filesystem=xdg-videos` and `--filesystem=xdg-documents` to finish-args so users can send files by default; I personally would want the whole home directory included, but that's probably not the way to go for more privacy-concious users.

**Comment by Follpvosten** [comment]
Btw, if we can agree on the filesystems, I can file a PR adding them.

**Comment by SISheogorath** [comment]
It was a faulty merge of mine, that caused this issue, I'll revert the commit which should solve this. See: https://github.com/flathub/im.riot.Riot/commit/fcabb98521fc8c1ce10d16e10403cabd5ff97895

With this change we are back to the state of #33

**Comment by Follpvosten** [comment]
Thanks for that!
But I'd maybe propose adding more folders than just the downloads - I may be making assumptions here, but I think at least pictures and videos can be considered essential for a modern instant messenger.
May I PR and add those folders to the permissions?
