### ISSUE TITLE
No network access

### ISSUE THREAD

**Issue by DemiMarie** [flathub/im.riot.Riot#151]
Element can’t access the Internet.  Running `flatpak enter im.riot.Riot curl -o /dev/null http://1.1.1.1` results in `Couldn't connect to server`.

**Comment by SISheogorath** [comment]
The flatpak definitely requests it:

https://github.com/flathub/im.riot.Riot/blob/4cf3b8265c94cb7c02e3e48a2b0e0f52ad3e7583/im.riot.Riot.json#L16

This can mean two things:

1. You found a bug in flatpak
2. Something is broken with your setup

Does network work fine any outside?

**Comment by DemiMarie** [comment]
Networking works fine with `com.wire.WireDesktop`.  The problem persists after recreating my setup from scratch.  `--share=network` does not help.

**Comment by SISheogorath** [comment]
The thing is, the way flatpak works is, if you don't provide `--share=network`, it'll create a network namespace for the app and isolate it. If you set `--share=network` it'll not create that network namespace, means staying in the host namespace and therefore use the networking of your setup.

Could you provide a small example on how to reproduce the issue? For example, what OS do you use to run the flatpak and what flatpak version? This could help with further debugging.

**Comment by DemiMarie** [comment]
The OS is Fedora 32 on QubesOS.  Flatpak version is 1.8.3.  Just `flatpak install flathub im.riot.Riot` followed by `flathub run im.riot.Riot` reproduces the bug.

For debugging, I copied `/usr/sbin/ifconfig` into the container and ran it.  This showed that the only network interface was `lo`, which implies that `--share=network` was not honored.

**Comment by SISheogorath** [comment]
I can not reproduce the problem on F33 with the same flatpak version.

Can you double check your observation of not using the right network namespace, by checking the processes?

```
ls -la /proc/$$/ns/net

ls -la /proc/$(ps aux | grep -Pe '/app/Element/element-desktop$' | awk '{print $2}')/ns/net
```

The output should look like this:

```
ls -la /proc/115036/ns/net 
lrwxrwxrwx. 1 xxx xxx 0 Dec 16 22:14 /proc/115036/ns/net -> 'net:[4026532008]'

ls -la /proc/115500/ns/net 
lrwxrwxrwx. 1 xxx xxx 0 Dec 16 22:17 /proc/115500/ns/net -> 'net:[4026532008]'
```

Means the latter should be the same, if they aren't, please check `flatpak info im.riot.Riot -M` To verify the permissions. It should look like this:

```
flatpak info im.riot.Riot -M 
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=all;
filesystems=xdg-download;xdg-run/keyring;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk
org.freedesktop.Notifications=talk
org.kde.StatusNotifierWatcher=talk
org.kde.StatusNotifierItem-2-1=own
```

Also, since you are on QubesOS, could you verify that you AppVM is allowed to access the network?

**Comment by DemiMarie** [comment]
> I can not reproduce the problem on F33 with the same flatpak version.
> 
> Can you double check your observation of not using the right network namespace, by checking the processes?
> 
> ```
> ls -la /proc/$$/ns/net
> 
> ls -la /proc/$(ps aux | grep -Pe '/app/Element/element-desktop$' | awk '{print $2}')/ns/net
> ```

```
$ ls -la /proc/self/ns/net
lrwxrwxrwx 1 user user 0 Dec 16 18:06 /proc/self/ns/net -> 'net:[4026531904]'

$ ls -la /proc/3600/ns/net
lrwxrwxrwx 1 user user 0 Dec 16 18:06 /proc/3600/ns/net -> 'net:[4026531904]'

$ ps 3600
    PID TTY      STAT   TIME COMMAND
   3600 pts/2    Sl+    0:01 /app/Element/element-desktop
```

> The output should look like this:
> 
> ```
> $ ls -la /proc/115036/ns/net 
> lrwxrwxrwx. 1 xxx xxx 0 Dec 16 22:14 /proc/115036/ns/net -> 'net:[4026532008]'
> 
> $ ls -la /proc/115500/ns/net 
> lrwxrwxrwx. 1 xxx xxx 0 Dec 16 22:17 /proc/115500/ns/net -> 'net:[4026532008]'
> ```
> 
> Means the latter should be the same, if they aren't, please check `flatpak info im.riot.Riot -M` To verify the permissions. It should look like this:
> 
> ```
> $ flatpak info im.riot.Riot -M 
> [Context]
> shared=network;ipc;
> sockets=x11;pulseaudio;
> devices=all;
> filesystems=xdg-download;xdg-run/keyring;
> 
> [Session Bus Policy]
> org.freedesktop.portal.Fcitx=talk
> org.freedesktop.Notifications=talk
> org.kde.StatusNotifierWatcher=talk
> org.kde.StatusNotifierItem-2-1=own
> ```

I get the same result.

> Also, since you are on QubesOS, could you verify that you AppVM is allowed to access the network?

It is.

However, I do get the following results from the following operations:

```
$ flatpak enter com.wire.WireDesktop curl -o /dev/null http://1.1.1.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0   2786      0 --:--:-- --:--:-- --:--:--  2786
$ flatpak enter im.riot.Riot curl -o /dev/null http://1.1.1.1
curl: (7) Couldn't connect to server
```

**Comment by DemiMarie** [comment]
Problem seems to be that Element uses its own sandbox.  If I pass `--no-sandbox` to Element, the problem goes away, but Element crashes due to what I believe is insufficient space in `/dev/shm`.  The AppVM I am using only has 2400MiB of RAM, so Flatpak is likely making a `/dev/shm` that is too small.

**Comment by SISheogorath** [comment]
I was able to reproduce it here as well. The curl call fails, because `flatpak enter im.riot.Riot` selects the background process that Element creates, not the main sandbox. When you select the main sandbox, it worked here. This is due to the background process being isolated from network, therefore having an own network namespaces.

You can find all running sandboxes using `flatpak ps`. Uusually 2 processes show up and only one of them has internet access as we use zypak for sandboxing chromium/electron.

**Comment by DemiMarie** [comment]
Thank you so much for your analysis, @SISheogorath!  That leaves the question of how to fix the problem.

I noticed that [Wire](/flathub/com.wire.WireDesktop) works fine, perhaps because it doesn’t sandbox its renderer.

**Comment by Erick555** [comment]
wire flatpak uses same sandbox as riot.

**Comment by DemiMarie** [comment]
This turned out to be a few different bugs:

- Running from the terminal leads to hangs.  Running from the desktop icon works.
- If I start the verification process, but don’t finish it, the UI hangs.
- I had distrusted the root certificate for https://vector.im, which caused symptoms that were outwardly similar to network problems.

Closing, as none of these are specific to the Flatpak.

**Comment by DemiMarie** [comment]
@SISheogorath and @Erick555 thank you so much for your assistence.
