### ISSUE TITLE
Flatpak gives all kinds of problems

### ISSUE THREAD

**Issue by 35609902357** [flathub/im.riot.Riot#161]
I installed the Flatpak app on Fedora 33 and it hangs at login screen (not the first login where you must input username/password), the call function doesn't work (there's no "user started call" indication but there's only the "user ended call" indication. I also tried it with the GNOME DE since I read Flatpaks work better with Wayland and it's even worse, it brings me to the login screen (the one where you must input username/password), but if I move the data to another distro it's actually logged in. I don't have these issues on Debian, but to be fair I don't have any issues with other Flatpaks either, they all work as expected on Fedora.

**Comment by vchernin** [comment]
I cannot reproduce any of these issues on fedora 34 silverblue (gnome). All the functions you describe as not working in the element flatpak work correctly for me.
Are you still able to reproduce these issues now?
