### ISSUE TITLE
SSL certificate authority errors when connecting to homeserver

### ISSUE THREAD

**Issue by jfrederickson** [flathub/im.riot.Riot#169]
I'm currently experiencing issues with the Flatpak release of Element when attempting to connect to my homeserver. Looking at the requests in developer tools, it appears Element is failing to validate the SSL cert of my homeserver, but it's a valid Let's Encrypt cert. (Homeserver is at https://terracrypt.net, you can check the cert that it's serving if you wish.)

Element Flatpak version: 1.7.23
`flatpak` version: 1.10.1
OS: Guix System at revision a2ece4d

![Screenshot from 2021-03-21 22-41-34](https://user-images.githubusercontent.com/1923178/111933893-c0d76080-8a96-11eb-8007-4898b76e03d9.png)

**Comment by SISheogorath** [comment]
I guess it might be due to serving multiple certificates, where one of them expired.

https://www.ssllabs.com/ssltest/analyze.html?d=terracrypt.net&hideResults=on

**Comment by jfrederickson** [comment]
That would be ERR_CERT_DATE_INVALID though, not ERR_CERT_AUTHORITY_INVALID.

And that second cert shouldn't matter? It's not being served for the terracrypt.net vhost, only matrix-client.terracrypt.net, which no longer points to that server. Not actually sure why that site was testing it; I guess it tries to enumerate hosts that the web server is looking for or something.

**Comment by SISheogorath** [comment]
I just tested this locally. At least now this homeserver doesn't seem to cause any issues. Feel free to re-open if the issue appears again.
