### ISSUE TITLE
Invisible icon in notification area with desktop version on Linux (Flatpak version on Xubuntu)

### ISSUE THREAD

**Issue by gdurif** [flathub/im.riot.Riot#172]
### Description

Using Element-desktop on Linux (Xubuntu/XFCE), especially the Flatpak install from Flathub (https://flathub.org/apps/details/im.riot.Riot), the Element icon in the notification area is invisible despite a dedicated place.

c.f. attached screen shot (3rd spot from the left)

![element_missing_notification_icon](https://user-images.githubusercontent.com/38720408/114401481-7c6d4b00-9b92-11eb-8e16-0fc98c9cc318.jpg)

I did try to change the area background color to be sure it was not some color superposition issue.

It can be noted that I can use the Element "invisible" icon as if it was visible, e.g. by clicking on it to Show/Hide Element desktop, or to quit.

Here is the notification area when running Element-desktop built from the official repository:

![element_notification_icon](https://user-images.githubusercontent.com/38720408/114401485-7d05e180-9b92-11eb-907f-9b426801dae7.jpg)

### Steps to reproduce

- install from Flathub  (with command `flatpak install flathub im.riot.Riot`)
- run Element-Desktop (e.g. with command `flatpak run im.riot.Riot`)

-> no visible Element icon in the notification area (c.f. attached screenshot)

### Version information

- **Platform**: desktop
- **OS**: Xubuntu 18.04.5 LTS / XFCE 4.12
- **Version**: 1.7.24

**Comment by vchernin** [comment]
So this issue doesn't occur with .deb builds? It's probably a matter of the flatpak not shipping/configuring the icons identically to the .deb. Maybe we aren't supplying a lower resolution version of the icon or something?

**Comment by gdurif** [comment]
Hello, sorry I did not update this. The problem was fixed with the latest update.
