### ISSUE TITLE
Support for Spaces - Public Beta?

### ISSUE THREAD

**Issue by MichaelTunnell** [flathub/im.riot.Riot#179]
Are there plans for the Flatpak to support the Public Beta of Spaces that Element just released today?

https://element.io/blog/spaces-the-next-frontier/

**Comment by ljrk0** [comment]
This would simply need an update to the 28 minor release, proposed by #178

**Comment by SISheogorath** [comment]
This should be fixed as soon as the new version is rolled out (merge + build, expect 3-12 hours until it reach all edges of the world) :) Will close it for now.

**Comment by MichaelTunnell** [comment]
Awesome, thanks! that's so fast that it kind of blows my mind. :D
