### ISSUE TITLE
no access to home dir

### ISSUE THREAD

**Issue by crabmanX** [flathub/im.riot.Riot#19]
the sandboxpermissions should use --filesystem=home so that  e.g. the upload button works

**Comment by TingPing** [comment]
`flatpak override --user im.riot.Riot --filesystem=home`. I don't think there is a right answer of what should be exposed by default.

**Comment by crabmanX** [comment]
overriding the permissions is certainly a solution for experienced users, but most users who just install riot from flathub will notice that e.g. sending files, changing the user avatar etc. doesnt work and think its broken. This will reflect poorly on riot/flathub

**Comment by SISheogorath** [comment]
duplicate #33
