### ISSUE TITLE
high cpu usage > 100%

### ISSUE THREAD

**Issue by cmurf** [flathub/im.riot.Riot#193]
This just started today, I haven't previously seen it and there's been no system or element updates. I'm also not sure what information to provide so here are the basics.

```
# flatpak info im.riot.Riot

Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.31
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 262.9 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: bf5abb4501459dd3837b5073ff41209785d677c9ab515301e57c056f1a95c505
      Parent: d111c2862c624bcf29e82fb04d1f5dedc83445fb6f36604b81adf663adbd3363
     Subject: Update element-desktop_1.7.30_amd64.deb to 1.7.31 (5b4b92c8)
        Date: 2021-06-21 20:37:42 +0000
```

top
```
15379 chris     20   0   50.5g 233280  89620 R 105.3   1.5   6:21.85 element-desktop                                                                                                             
```
50G virt seems unreasonable.

/proc/pid/status
```
Name:	element-desktop
Umask:	0022
State:	R (running)
Tgid:	15379
Ngid:	0
Pid:	15379
PPid:	15333
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	128
Groups:	10 983 1000 
NStgid:	15379	61	4
NSpid:	15379	61	4
NSpgid:	15320	0	0
NSsid:	15320	0	0
VmPeak:	57031252 kB
VmSize:	52993272 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  327900 kB
VmRSS:	  229528 kB
RssAnon:	  139908 kB
RssFile:	   89012 kB
RssShmem:	     608 kB
VmData:	  352996 kB
VmStk:	     132 kB
VmExe:	  100788 kB
VmLib:	   26104 kB
VmPTE:	    2288 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	21
SigQ:	0/62457
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001002
SigCgt:	00000001c0010000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000000000000000
CapAmb:	0000000000000000
NoNewPrivs:	1
Seccomp:	2
Seccomp_filters:	2
Speculation_Store_Bypass:	vulnerable
SpeculationIndirectBranch:	always enabled
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	14643
nonvoluntary_ctxt_switches:	3442
```

Attaching strace, but I can't make heads or tails out of it.
[element-strace.txt](https://github.com/flathub/im.riot.Riot/files/6735076/element-strace.txt)

**Comment by cmurf** [comment]
Trying app.element.io on Firefox 89, and the problem isn't happening there.

**Comment by vchernin** [comment]
Does this occur with Element's official .deb builds? (if you're on Ubuntu or Debian).
If it also occurs there you should report this upstream at https://github.com/vector-im/element-web/issues

**Comment by cmurf** [comment]
I'm on Fedora 34 so I'm not sure I can or that it would be an apples to apples comparison, since the database is in ~/.var - another datapoint is that this problem is happening with only one room, which is encrypted. If I click on that room to make it in focus, the problem happens. If I click on any other room (none of which are encrypted) to make it in focus, the problem doesn't happen.

**Comment by vchernin** [comment]
Is that one room your only encrypted room, or are there other encrypted rooms that are fine?

**Comment by cmurf** [comment]
That one room is the only encrypted room. And after quite a few days, nearly a week, it seems to have settled down. I suspect it's related to a migration, and it was decrypting older messages in that room with a previous system's key, and reencrypting locally? Is that something that can happen? I've got no idea how matrix+element encryption works.

**Comment by vchernin** [comment]
It's indeed possible it was doing some background processing or something.

In the settings menu there are a bunch of settings for encryption, some of those might help you "refresh" the state of the encryption on your Element install.

**Comment by cmurf** [comment]
OK I think this can be closed now. Thanks.
