### ISSUE TITLE
The sidebar is not able to collapse properly.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/im.riot.Riot#217]
![2021-09-19T19-26-22 DAT BIN](https://user-images.githubusercontent.com/42837531/133940420-fbf9f0a3-21b7-487b-b637-8a27ee8876ba.PNG)

**Comment by vchernin** [comment]
Can you reproduce this with Element Web, or Desktop from non-Flatpak? If so this bug is best reported here: https://github.com/vector-im/element-web

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/im.riot.Riot/issues/217#issuecomment-922537292

This is reproducible at http://github.com/vector-im/element-web.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/im.riot.Riot/issues/217#issuecomment-922538826

This problem has been reported at http://github.com/vector-im/element-web/issues/19097 and http://github.com/vector-im/element-web/issues/19098.
