### ISSUE TITLE
--force-device-scale-factor flag isn't recognized

### ISSUE THREAD

**Issue by Lortegap** [flathub/im.riot.Riot#233]
As title says, unlike with other flatpaks like discord, --force-device-scale-factor  isn't recognized by element. 
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/element  --force-device-scale-factor=1 --file-forwarding im.riot.Riot @@u %U @@`
returns  " error: Unknown option --force-device-scale-factor=2 "
According to https://github.com/vector-im/element-web/issues/3132 , it should work.

**Comment by SISheogorath** [comment]
You are currently passing this parameter to flatpak, but not to the script inside you have to put the parameter behind `im.riot.Riot`.

**Comment by Lortegap** [comment]
hmm, i thought for Element it'd just work, because for Discord, it does..

**Comment by SISheogorath** [comment]
It might even will, if you stop trying to configure flatpak instead of element.

The command you are looking for looks like this:
```shell
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/element --file-forwarding im.riot.Riot --force-device-scale-factor=1  @@u %U @@
```

**Comment by Lortegap** [comment]
oh, thanks so much
