### ISSUE TITLE
Use proper FileChooser and Document portals

### ISSUE THREAD

**Issue by compu42** [flathub/im.riot.Riot#244]
The current version still uses the old way of accessing files by simply opening parts of the filesystem up to the sandbox. The new portals should be leveraged for a more convenient and safer system.

https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.FileChooser

**Comment by SISheogorath** [comment]
Please see #33 

This is something burried in Electron and might soon be fixed, but as far as I know not yet.

**Comment by vchernin** [comment]
In my testing the file chooser portal works in Electron 16 upstream, so hopefully that's also true for Element.
