### ISSUE TITLE
crashes on fedora 36

### ISSUE THREAD

**Issue by damnms** [flathub/im.riot.Riot#256]
because there is no one left who creates fedora builds for element (thanks to [t0dd/taw](https://copr.fedorainfracloud.org/coprs/taw/element/) for his previous builds!), i tried the flathub version. 
unfortunately, that crashes on fedora 36 which is going to be beta-released in 1-2 weeks.

zypak-helper killed by SIGABRT
cmdline: /app/bin/zypak-helper host /app/Element/element-desktop
container_cmdline: bwrap --args 38 element

**Comment by SISheogorath** [comment]
does this problem only appear with Element or do other Electron-based apps also fail?

**Comment by damnms** [comment]
somehow it works now, could be one of the latest fedora updates, so no element problem ;)
