### ISSUE TITLE
Stuck on white screen (flatpak-spawn: Unknown option --envSBX_NET_NS=1)

### ISSUE THREAD

**Issue by schildbach** [flathub/im.riot.Riot#267]
Since a week or so, I've only got a **white screen** in the Flatpak version of the Desktop client. I've already tried uninstalling/reinstalling but it didn't help. Is this a known problem? How can I collect and provide logs, I'm not familiar with administration of Flatpak unfortunately.

I believe the problem started with the version that was released before 1.10.10 (probably 1.10.9?)

This on Ubuntu 20.04.4 LTS and the Flatpak 1.6.5 that comes with it.

**Comment by schildbach** [comment]
I think I just found out how to acquire logs:

```
$ flatpak run im.riot.Riot
[3 zypak-helper] Portal v4 is not available
/home/aschildbach/.var/app/im.riot.Riot/config/Element exists: yes
/home/aschildbach/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 15:13:38.712: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:13:38.713: Failed to load module "canberra-gtk-module"
[3:0416/151338.745995:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0416/151338.746050:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
flatpak-spawn: Unknown option --envSBX_NET_NS=1
Try "flatpak-spawn --help" for more information.
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
flatpak-spawn: Unknown option --envSBX_NET_NS=1
Try "flatpak-spawn --help" for more information.
[33:0416/151338.998434:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by spezifisch** [comment]
Same problem here on Ubuntu 20.04.4 LTS.

Element 1.10.8 still works but since 1.10.9 it's stuck on the white screen.
Temporary workaround is to downgrade to .8 with:

```shell
sudo flatpak update --commit=54634505e32f85174a35ddb9aad2ce0361ca422c2ef9d04cef1707093711e987 im.riot.Riot
```

**Comment by schildbach** [comment]
The workaround works for now (-:

**Comment by SISheogorath** [comment]
I think this is related to the update of the base-app's zypak release:

https://github.com/flathub/org.electronjs.Electron2.BaseApp/commit/38d95cdea9d262720a2f1da2229b32ed260038b6

@refi64 could you look into this? Is there a new flatpak version requirement?

**Comment by refi64** [comment]
This should be fixed with Zypak v2022.04, I'll be merging in the changes to the baseapp once they're available there.

**Comment by SISheogorath** [comment]
@refi64 you rock!

**Comment by refi64** [comment]
It's [in the baseapp now](https://github.com/flathub/org.electronjs.Electron2.BaseApp/pull/33) and [publishing](https://flathub.org/builds/#/builders/29/builds/47017), once that's done I *think* you can just trigger a rebuild of this app and it should be fixed.

**Comment by refi64** [comment]
Oh the build is already published :sweat_smile: didn't realize it'd be that fast

**Comment by schildbach** [comment]
@spezifisch Quick question, how do I un-pin from the specific commit?  Just `sudo flatpak update im.riot.Riot` keeps me at the pinned commit.

**Comment by 0xC0ncord** [comment]
This is fixed for me after updating to the latest version that came out today. Thanks!

**Comment by spezifisch** [comment]
> @spezifisch Quick question, how do I un-pin from the specific commit? Just `sudo flatpak update im.riot.Riot` keeps me at the pinned commit.

I think you need to omit the `sudo` for this if you installed the package user-locally. It works for me at least:

```console
$ flatpak update im.riot.Riot 
Looking for updates…


        ID                   Branch         Op        Remote         Download
 1. [✓] im.riot.Riot         stable         u         flathub        34.7 MB / 116.6 MB

Updates complete.
```
