### ISSUE TITLE
Host CA are not used

### ISSUE THREAD

**Issue by ficoos** [flathub/im.riot.Riot#28]
Custom CAs are not taken from the host. There is no other way to add a CA to the sandbox. This means that self signed home servers can't be used.

**Comment by TingPing** [comment]
This is something to discuss over at flatpak/flatpak.

The problem is openssl as for gnutls it should just work.

**Comment by LorbusChris** [comment]
I had hoped this would be fixed by the latest p11-kit release, which is now in the 18.08 base, but it wasn't :(

**Comment by Erick555** [comment]
@LorbusChris firefox should be potentially fixed by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1145 (not in flathub yet). I don't know about riot.

**Comment by SISheogorath** [comment]
Is this solved by the mentioned feature above being merged?

**Comment by TingPing** [comment]
Riot uses Electron which has a bundled fork of OpenSSL, it is not in any way affected by that NSS patch.

**Comment by SISheogorath** [comment]
@TingPing wouldn't it makes sense to mount the host's CA directory as read-only into the runtime? (Which would me this issue would also be addressed on a lower level)

**Comment by TingPing** [comment]
My very first comment was "This is something to discuss over at flatpak/flatpak." and that remains the case.

This isn't a package issue. Perhaps you are right that we can safely pass them into the sandbox. I don't know and it needs discussion.

**Comment by LorbusChris** [comment]
I created an issue for this upstream some time ago: https://github.com/flatpak/flatpak/issues/2721

**Comment by SISheogorath** [comment]
Then let's close it on the app level. People should be able to find the issue upstream from here :)
