### ISSUE TITLE
Element ignore filesystem overrides

### ISSUE THREAD

**Issue by tsumi** [flathub/im.riot.Riot#292]
I just installed element and noticed that file attachment form show all my home directory and even all my filesystem
I tried to override it but changes are ignored, i can still attach anything from my home dir:

my `~/.local/share/flatpak/overrides/im.riot.Riot` actually is:

```
[Context]
filesystems=!xdg-desktop;!xdg-documents;!xdg-download;!xdg-videos;!xdg-pictures;!xdg-music;~/Element
```

I also tried something more explicit like:

```
[Context]
filesystems=!host;!home;!xdg-desktop;!xdg-documents;!xdg-download;!xdg-videos;!xdg-pictures;!xdg-music;~/Element
```

But the issue persist.
Changes are similar to override that i use for Discord and on this app works fine, showing only the ~/Discord folder and nothing else

OS: Fedora 35 MATE
Flatpak version: 1.12.7

Any help about it?
Thanks

**Comment by SISheogorath** [comment]
This indicates that Element is using Portals. I just tried to reproduce the issue and it makes all sense, that Electron is now capable, which also means, we can probably get rid of all the current filesystem permissions.

I need to do some further checking, but this could be very nice.

**Comment by tsumi** [comment]
I don't really think that bypass filesystem permissions is a good thing... I like flatpak for the sandbox...

**Comment by SISheogorath** [comment]
Portals don't bypass the sandbox. Portals dynamically configure file access permissions for exactly the files you select. This makes the access seemless, while the sandbox cna be enforced without any implicit access.

**Comment by tsumi** [comment]
Is there still a way to deny access to homedir except for specific paths?

**Comment by SISheogorath** [comment]
No, portals just mimic the regular file-open dialogue. If you want to deny access to something you have to use the same mechanisms you would use for an unsandboxed application. Keep in mind, that portals don't bypass the sandbox, they just make the experience seamless from the outside. The application inside has no way to secretly access files you haven't explicitly selected to be shared.

https://docs.flatpak.org/en/latest/desktop-integration.html?highlight=portals#portals

**Comment by tsumi** [comment]
Oh, interesting, thanks for the clarifications
