### ISSUE TITLE
runtime and platform update 22.08 breaks cursor theme and size on wayland.

### ISSUE THREAD

**Issue by queeup** [flathub/im.riot.Riot#297]
I am using this options to fix wayland fractional scaling blury font issue:
`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`

Logseq flatpak also affected: https://github.com/flathub/com.logseq.Logseq/issues/11

[Ekran Kaydı - 2022-09-16 14-30-50.webm](https://user-images.githubusercontent.com/87835/190630107-8a4497e3-1d7b-4eb0-9307-5ffe8799f2d2.webm)

**Comment by SISheogorath** [comment]
Given that the runtime [already has an issue open for this problem](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1484) and it's better tracked and solved there than here, I will close this here, especially since it affects various apps.

**Comment by queeup** [comment]
Maybe revert back to 21.08 until this issue solved?
