### ISSUE TITLE
GTK window decoration integration

### ISSUE THREAD

**Issue by fbruetting** [flathub/im.riot.Riot#31]
Would be pretty cool if Riot could make use of the GTK header bar features and integrate the top bar into the header bar. 😎 Currently, it looks quite out of place on Gnome desktops. 😬

**Comment by TingPing** [comment]
Why are you reporting that here?

**Comment by fbruetting** [comment]
There was just vector-im/riot-web, so I assumed that this repository brings the webpage into a desktop app. Now I looked there again and saw that I can mention desktop bugs in  “riot-web”, too… pretty irritating… sorry!
