### ISSUE TITLE
Tray Icon not showing

### ISSUE THREAD

**Issue by action-server** [flathub/im.riot.Riot#319]
In the latest update with flatpak-commit: "ea6cb2947ca7435c512ebeb0a895f863f85a46ecdb5c1077eed717e4e6ebf370", the tray icon isn't showing.

I downgraded to the previous flatpak-commit: "9bd0c958912a8187b019b3a11260da2e6c241b92a6e570fd0efc8b2f53186310" to fix the issue temporarily.

**Comment by SISheogorath** [comment]
Amazing, it seemw to be indeterministic: https://github.com/flathub/im.riot.Riot/issues/317

**Comment by action-server** [comment]
I have taken a look at the commits after v1.11.16 of [element desktop](https://github.com/vector-im/element-desktop), and noticed, that they have upgraded to electron v22.0.0, so i went and checked the electron github page and found [this](https://github.com/electron/electron/issues/36602) open issue there.
Seems like we just have to wait it out.

**Comment by witchent** [comment]
What happens when you disable and enable showing the tray icon in the settings page? In my case (using Kubuntu here) that restores the icon until you shutdown the app and restart it again. Just want to know if it is the same problem or an unrelated one

**Comment by hunter2k01** [comment]
Funny enough, I have this issue on MATE but not on KDE too.
