### ISSUE TITLE
Grants ownership of the entire org.kde.* session bus hierarchy

### ISSUE THREAD

**Issue by foresto** [flathub/im.riot.Riot#327]
The manifest currently includes `--own-name=org.kde.*`, which allows the app to impersonate any KDE session bus service it likes, including the user's keyring manager. Obviously, this is terrible for security and privacy.

The goal of that permission is to allow tray icons (aka status icons) that follow Freedesktop's flawed naming convention.

We can achieve that goal without opening up such a risky hole in the sandbox. I will submit a patch soon.

**Comment by bbhtt** [comment]
This was removed in https://github.com/flathub/im.riot.Riot/commit/d92a129d36946dc90efd03487cd0c02e0e899a40 and has been working without any issues as far as I know. Closing.

Thanks.
