### ISSUE TITLE
Crash when sharing screen on 1:1 calls

### ISSUE THREAD

**Issue by yajo** [flathub/im.riot.Riot#334]
Hello friends!

After a lot of time without any issues on Element calls, it turns out that recently it started crashing when I attempt to share the screen in a 1:1 call.

I don't know very well how to diagnose this.

System: Fedora Linux 37.20230115.0 (Silverblue), wayland, GNOME 43.2, AMD Radeon™ Graphics.

**Comment by telometto** [comment]
Same issue here; same hw.

**Comment by cam-rod** [comment]
Did this issue start occuring in the last two weeks? It may be related to the changes in #325 (in which case I need to update #337)

**Comment by telometto** [comment]
@cam-rod I'm not entirely sure, but not long ago it used to work fine. You could be right about the time frame, but I cannot answer with 100% certainty.

**Comment by yajo** [comment]
I updated my comment https://github.com/flathub/im.riot.Riot/issues/334#issuecomment-1427650723 because I got misleaded by the fact that upstream screen sharing got broken in 1.11.15 as you can see in https://github.com/vector-im/element-web/issues/23808. In reality, for the flaptak, the last working release was 1.11.16.

The commit range where the failure exists is [this one](https://github.com/flathub/im.riot.Riot/compare/6c602bde1bfabdb21e26419505f0820728b852d0...e9f8d98152e30486a5ad6801efeda30f6d2ec864). Weird, it's just a normal package update. I hope this can help to see what changed upstream that broke the package!

**Comment by byquanton** [comment]
No longer Crashes with #387 🥳 
(But it may open too many Screen sharing Portals)

**Comment by byquanton** [comment]
-> https://github.com/electron/electron/issues/39043

**Comment by yajo** [comment]
I opened https://github.com/vector-im/element-web/issues/26014 but they told me this must be fixed downstream.

Indeed that code seems to be what opens the dialogs in loop. Maybe we could add a patch here to avoid that?
