### ISSUE TITLE
Crash on reopening

### ISSUE THREAD

**Issue by NetDwarf** [flathub/im.riot.Riot#335]
With the latest version (commit: `d3ceae47addf2d3a45e569c1a9ca4cb80d0497af2628ab8936b16885784bc57a`)
Element crashes when trying to get it to foreground (after being sent to background). 

**Setup:**
Debian
Gnome
Wayland

**Error message:**
```
ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@31: error 0: gtk_shell::get_gtk_surface already requested

/app/bin/element: line 16:     3 Trace/breakpoint trap   env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```
**Additional info:**
This seems to be introduced by commit `c897044b0885b547e76702886039993c2a7fc73a9054ab36b91997b43984814b` and is not present in the commit that precedes it.

![RiotBug](https://user-images.githubusercontent.com/14839491/217846610-1b88c619-4b08-48ee-ac52-52ee36f306b1.png)

**Comment by cam-rod** [comment]
Also encountering this issue and error message on Fedora 37 in Wayland. Also, I found that when using Ctrl-Q to close the app, it freezes for a few seconds, and then doesn't close until Ctrl-Q is used again. After this point, the toolbar icon will briefly appear during boot before disappearing. I was only able to restore it by reinstalling Element.

Removing Ozone platform flags from [the launch script](https://github.com/flathub/im.riot.Riot/blob/master/element.sh) fixes both issues. My guess is Element isn't fully compatible with Wayland and the changes in #325 yet  (with the exception of `--enable-features=WebRTCPipeWireCapturer` for both Wayland and X11, which didn't cause issues).

**Comment by hoh** [comment]
I am encountering the same issue using NixOS - KDE - Xorg, same commit.

**Comment by CicadaCinema** [comment]
I am still encountering a crash with commit `a2ba54cdc742926e6b99fe248c68e833791478330dde5daa8107457e4832c451`:

`sudo flatpak update --commit=a2ba54cdc742926e6b99fe248c68e833791478330dde5daa8107457e4832c451 im.riot.Riot`

**Log:**
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/element --file-forwarding im.riot.Riot @@u %U @@
/home/jazz/.var/app/im.riot.Riot/config/Element exists: yes
/home/jazz/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0215/110430.257193:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0215/110430.257259:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
... snip ...
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: user interaction failed]
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by NetDwarf** [comment]
`Error getting the event index passphrase out of the secret store`

@CicadaCinema this seems like a very different error message and is probably also not only happening on reopening but on start.

**Comment by CicadaCinema** [comment]
> `Error getting the event index passphrase out of the secret store`
> 
> @CicadaCinema this seems like a very different error message and is probably also not only happening on reopening but on start.

Thank you, my issue looks more like https://github.com/flathub/im.riot.Riot/issues/339 , which seems to have been a common problem with this flatpak for a while.

**Comment by NetDwarf** [comment]
Can confirm that this issue is fixed in commit `33a595252d302821f56ab0de783334273df3a4d317c70884a8444c925628ce34`. Thanks @cam-rod for making us aware!
