### ISSUE TITLE
Open program, runs maybe a minute, everything works, crashes.

### ISSUE THREAD

**Issue by CipherOps** [flathub/im.riot.Riot#339]
Had this issue on openSUSE Tumbleweed, figured it was just normal issues for me with that distoro, currently on Debian, installed im.riot.Riot from Flathub, same issue, logs below of what happens when running from terminal.
```
tyler@workstation:~/bin$ flatpak run im.riot.Riot 
/home/tyler/.var/app/im.riot.Riot/config/Element exists: yes
/home/tyler/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0220/220500.502756:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0220/220500.502824:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
/app/bin/element: line 16:     3 Trace/breakpoint trap   env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by CicadaCinema** [comment]
This seems to be a common issue with this flatpak, and is related to the functionality of message search in encrypted rooms. If you can tolerate not being able to search the encrypted rooms you are in, try disabling this option under `Settings > Security & Privacy > Message search > Manage > Disable` and see if the issue goes away.

My own laptop and desktop are experiencing the same symptoms, and in both cases, the issue gets resolved upon disabling message search, as I suggested above.

## This is a common problem!

See:
- https://github.com/vector-im/element-web/issues?q=is%3Aissue+%22Error+getting+the+event+index+passphrase+out+of+the+secret+store%22
- https://github.com/flathub/im.riot.Riot/issues?q=is%3Aissue+%22Error+getting+the+event+index+passphrase+out+of+the+secret+store%22+

It looks like people may be conflating unrelated crashes with this bug which is clearly tied to the message search feature.

## Example reports of this issue

> ```
> ...
> Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
> [55:0217/153453.726296:ERROR:broker_posix.cc(40)] Recvmsg error: Соединение разорвано другой стороной (104)
> /app/bin/element: строка 16:     3 Ловушка трассировки/останова                              (образ памяти сброшен на диск) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
> ```

_Originally posted by @dmmarkov in https://github.com/vector-im/element-web/issues/24561#issuecomment-1434582531_

> ```
> ...
> Error getting the event index passphrase out of the secret store [Error: user interaction failed]
> /app/bin/element: line 16:     3 Trace/breakpoint trap   env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
> ```

_Originally posted by @hunter2k01 in https://github.com/vector-im/element-web/issues/23311#issuecomment-1430002796_

> Application keep crashing after a few seconds-minutes.

_Originally posted by @azzid in https://github.com/flathub/im.riot.Riot/issues/329#issue-1559923761_

> This might be related to the message search functionality. I remember that disabling that option worked for me some weeks back when I had the same issue

_Originally posted by @martijk in https://github.com/flathub/im.riot.Riot/issues/329#issuecomment-1434416658_

> ```
> $ flatpak run -v im.riot.Riot
> ...
> Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
> /app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
> ```

_Originally posted by @jellersby in https://github.com/flathub/im.riot.Riot/issues/280#issuecomment-1350404572_

## Logs

### My laptop running Fedora 37
<details>
  <summary>Click to expand</summary>

```
$ flatpak run im.riot.Riot 
/home/jazz/.var/app/im.riot.Riot/config/Element exists: yes
/home/jazz/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0221/144939.495745:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0221/144939.495806:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
/app/bin/element: line 16:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```
</details>

### My desktop running Fedora 37
<details>
  <summary>Click to expand</summary>

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/element --file-forwarding im.riot.Riot @@u %U @@
/home/jazz/.var/app/im.riot.Riot/config/Element exists: yes
/home/jazz/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0215/110430.257193:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0215/110430.257259:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
... snip ...
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: user interaction failed]
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```
</details>

Interestingly, the laptop does not show the penultimate line `Error getting the event index passphrase out of the secret store [Error: user interaction failed]` in the log. However, the issue on my laptop is also fixable by disabling message search.

**Comment by CicadaCinema** [comment]
The following users claim that downgrading can fix the issue, but it seems to me that one can only downgrade to a version which is listed in the output of the command `flatpak remote-info --log flathub im.riot.Riot`; that is to say - one of the last 10 released versions.

> _P.S. Screw that. Rolled back to old version, works fine._
> 
> ```
> sudo flatpak update --commit=4dd3fa84bd6bd2a4ffd4e4b66e4dc834372fb2e75a99b199f7d46c747ff7c6c2 im.riot.Riot
> ```

_Originally posted by @Orhideous in https://github.com/vector-im/element-web/issues/24108#issuecomment-1365824210_

> This issue exists for me from the upgrade of version 1.11.10 to 1.11.15

_Originally posted by @YourSandwich in https://github.com/vector-im/element-web/issues/24108#issuecomment-1366758139_

**Comment by Marzal** [comment]
Thanks, with `--commit=8049c17aff993279fc4da0093f2df01f9f5d26672e4a17a0ee21227ea62c0f64` Element does work again.

**Comment by CipherOps** [comment]
I can confirm that disabling Message Search also resolves the issue, weird. Thank you! Hopefully a fix can be found in the future.

**Comment by CicadaCinema** [comment]
> Thanks, with `--commit=8049c17aff993279fc4da0093f2df01f9f5d26672e4a17a0ee21227ea62c0f64` Element does work again.

Doesn't work for me. Are you sure that Element still had some large number of messages to index when you tested this?

For some reason, on another one of my accounts, Element managed to index all ~4000-5000 messages. But my primary account has a lot more messages to index and Element crashes, as before.

### Logs from my laptop

<details>
<summary>Click to expand</summary>

```
$ echo "do I have anything in my ~/.var/app/im.riot.Riot?" && ls ~/.var/app | grep -i riot; echo "NO!" && flatpak install im.riot.Riot && sudo flatpak update --commit=8049c17aff993279fc4da0093f2df01f9f5d26672e4a17a0ee21227ea62c0f64 im.riot.Riot && flatpak run im.riot.Riot
do I have anything in my ~/.var/app/im.riot.Riot?
NO!
Looking for matches…

im.riot.Riot permissions:
    ipc      network      pulseaudio      wayland      x11      devices      file access [1]      dbus access [2]      bus ownership [3]

    [1] xdg-run/keyring, xdg-run/pipewire-0
    [2] org.freedesktop.Notifications, org.freedesktop.ScreenSaver, org.freedesktop.portal.Fcitx, org.kde.StatusNotifierWatcher
    [3] org.kde.*


        ID                   Branch         Op        Remote         Download
 1. [✓] im.riot.Riot         stable         i         flathub        115.1 MB / 117.9 MB

Installation complete.
[sudo] password for jazz: 
Looking for updates…


        ID                   Branch         Op        Remote         Download
 1. [✓] im.riot.Riot         stable         u         flathub        110.5 MB / 111.8 MB

Updating… ████████████████████ 100%  13.8 MB/s  00:00
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
        ID                   Branch         Op        Remote         Download
 1. [✓] im.riot.Riot         stable         u         flathub        110.5 MB / 111.8 MB

Updates complete.
/home/jazz/.var/app/im.riot.Riot/config/Element exists: no
/home/jazz/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0222/180203.793480:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0222/180203.793579:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/settings.js
- /app/Element/resources/app.asar/lib/ipc.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:88:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:101:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:100:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/settings.js',
    '/app/Element/resources/app.asar/lib/ipc.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
Opening URL:  vector://vector/webapp/?element-desktop-ssoid=tVvOQYzoZkjMjr3pQm1SBZlyeFR9R0KC&loginToken=syl_lKxizsQEnTEqealDXkwj_0KZGZm#/
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/settings.js
- /app/Element/resources/app.asar/lib/ipc.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:88:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:101:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:100:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/settings.js',
    '/app/Element/resources/app.asar/lib/ipc.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

</details>

**Comment by Marzal** [comment]
> > Thanks, with `--commit=8049c17aff993279fc4da0093f2df01f9f5d26672e4a17a0ee21227ea62c0f64` Element does work again.
> 
> Doesn't work for me. Are you sure that Element still had some large number of messages to index when you tested this?
> 
> For some reason, on another one of my accounts, Element managed to index all ~4000-5000 messages. But my primary account has a lot more messages to index and Element crashes, as before.
> ### Logs from my laptop
> Click to expand

No, I didn't. It should be another bug, because disabling search doesn't help if I update to the latest version.

**Comment by CicadaCinema** [comment]
> > > Thanks, with `--commit=8049c17aff993279fc4da0093f2df01f9f5d26672e4a17a0ee21227ea62c0f64` Element does work again.
> > 
> > 
> > Doesn't work for me. Are you sure that Element still had some large number of messages to index when you tested this?
> > For some reason, on another one of my accounts, Element managed to index all ~4000-5000 messages. But my primary account has a lot more messages to index and Element crashes, as before.
> > ### Logs from my laptop
> > Click to expand
> 
> No, I didn't check the number of messages. It should be another bug, because disabling search doesn't help if I update to the latest version.

So Element crashes for you with search indexing disabled, on the latest version? If yes, you are probably experiencing a different issue.

**Comment by SISheogorath** [comment]
I build kind of a workaround for the problem: #347 

Not entirely sure it definitely works, needs some more validation. Also not the greatest of fixes. Yet better than what we have, and given the time the issue has been around, I don't think it's going to disappear tomorrow. Since I don't know for how many people search actually works, it's opt-in rather than opt-out.

**Comment by williamd5** [comment]
I used https://software.opensuse.org/package/element-desktop and this works great for me. If you scroll down you will find "Fedora 37" -> community packages -> expert download. You now have commands to add the DNF repository and download the package from DNF, or you can directly download a binary.

**Comment by chimere2** [comment]
Just to add some info : 
On fresh installs of Fedora, the flatpak package works without problems on Fedora 35 (and I use it daily), but has never worked for me on Fedora 36 or 37, giving the above mentioned error message ("Error getting the event index...").

**Comment by evert** [comment]
Just switched from Ubuntu to Fedora, and also ran into these crashes. Disabling search also fixed this for me.

**Comment by SISheogorath** [comment]
This should be resovled by #357

If the problem still persists feel free to reopen

**Comment by YellowOnion** [comment]
Ahh yes, the community has to find a work around for bad decisions:

![image](https://github.com/flathub/im.riot.Riot/assets/364160/84aa8d64-0bca-4971-a948-55346094edc3)
