### ISSUE TITLE
Can't use ibus IME

### ISSUE THREAD

**Issue by wi24rd** [flathub/im.riot.Riot#34]
I'm using ibus rime to input Chinese, but it doesn't work in this app which doesn't pop up the input candidate.
Anyone also encounter this problem?

**Comment by SISheogorath** [comment]
Have the same problem. Seems to be related to https://github.com/flathub/io.atom.electron.BaseApp/issues/4

Seems to be fixed (on it's way to) upstream and needs to get down here over time.

**Comment by SISheogorath** [comment]
This should be fixed with the latest platform update (worked on my machine)
