### ISSUE TITLE
Mouse Cursor Extremely Small on HiDPI (4K) Displays Running Wayland

### ISSUE THREAD

**Issue by ethanrjones97** [flathub/im.riot.Riot#341]
Hello, I'm not quite sure when this started but when I started up the Flatpak recently and the mouse cursor is extremely small. 
My setup is 
- Fedora 37 
- GNOME 43.3
- 2x4K monitors 
- Using Wayland 
- With 200% scaling 

I run Lollypop, Telegram, and a few other apps in Flatpak and they do not have this issue. 

![image](https://user-images.githubusercontent.com/5385580/221470638-b99d7699-2e63-4f0b-8bf8-655b1a2797e0.png)

I've tried a few work around that are mentioned in various threads for similar bugs on other Flatpaks but they don't seem to do anything (`flatpak override ...` different variables or exposing different parts of the fs). One did mention it was related to an outdated FreeDesktop library. 

I can provide more information as needed, thanks.

**Comment by ell1e** [comment]
I have the same problem with Wayland and a Full HD display.

**Comment by LorbusChris** [comment]
possible a reoccurence of https://github.com/flatpak/flatpak/issues/740

**Comment by janvlug** [comment]
See how this was solved in Signal flatpak:
https://github.com/flathub/org.signal.Signal/commit/831398d6b89fc2ae75423ef4ee178898b9d2e908

**Comment by janvlug** [comment]
I tested the above by setting the variable in with Flatseal, and it works:
![image](https://user-images.githubusercontent.com/5903208/222902106-90c4cf6b-aa1e-44e3-92c9-47579ed47e01.png)
