### ISSUE TITLE
fcitx5 cannot popup in f38 flatpak riot

### ISSUE THREAD

**Issue by ww866** [flathub/im.riot.Riot#358]
https://paste.centos.org/view/9d180171

GTK_IM_MODULE=fcitx flatpak run im.riot.Riot --ozone-platform-hint=x11 
when I use above, it works.

**Comment by SISheogorath** [comment]
What happens if you use flatseal to disable the wayland socket?

**Comment by freundTech** [comment]
I have the same problem with ibus on fedora 38 (and 37). In that case disabling wayland access fixes the problem.

**Comment by bbhtt** [comment]
I think this is because Electron doesn't support IME under native wayland https://github.com/electron/electron/issues/33662

**Comment by SISheogorath** [comment]
Closing in favour of https://github.com/flathub/im.riot.Riot/issues/391
