### ISSUE TITLE
High CPU & disk I/O idling.

### ISSUE THREAD

**Issue by sqwwqw5** [flathub/im.riot.Riot#367]
Compared to the appimage from Appimagehub, the flatpak image utilizes way more resources in terms of CPU usage and disk I/O. Running both images side by side, it's very easy to observe the difference.

**Comment by SISheogorath** [comment]
Have you compared the same Element versions? Might be a regression, appimagehub has 1.11.23 while this flatpak runs 1.11.31.

**Comment by MatMaul** [comment]
Probably related to [this](https://github.com/vector-im/element-desktop/issues/959), it should be fixed on next version I believe.

**Comment by SISheogorath** [comment]
I'll close this one for now.
