### ISSUE TITLE
Window controls missing on Linux

### ISSUE THREAD

**Issue by julianfairfax** [flathub/im.riot.Riot#377]
Since the last update, the window controls are missing on Linux

![Screenshot from 2023-06-29 15-13-04](https://github.com/flathub/im.riot.Riot/assets/43753131/c0e0b20b-28a3-4f81-b896-1e1873e97fdd)

cc https://github.com/flathub/org.signal.Signal/issues/475; this is probably an Electron issue

**Comment by bbhtt** [comment]
Electron regression https://github.com/electron/electron/issues/38786

You can run it with `--nosocket=wayland` to fix it.

I'd advise, [not to force native wayland](https://github.com/flathub/im.riot.Riot/blob/3bfc0949831a1723da7f318ed5eaa1c88fa0efc9/element.sh#L5) on electron applications when they don't enable it by default or works on it actively and there are a bunch of issues regarding scaling popups etc. Users can enable it, if they want to.

**Comment by bbhtt** [comment]
Fixed in 1.11.37 released last week.
