### ISSUE TITLE
No close option in latest release

### ISSUE THREAD

**Issue by Naadiyaar** [flathub/im.riot.Riot#380]
![Screenshot from 2023-07-08 16-17-47](https://github.com/flathub/im.riot.Riot/assets/106643149/171ad85b-d202-4a91-8fc1-9098f52dcd15)

version 
```
Element version: 1.11.35
Olm version: 3.2.14
```

**Comment by mrdrogdrog** [comment]
Same problem. But only on wayland. Not on x11.

**Comment by A6GibKm** [comment]
To be precise this is a electron regression that can be seen in wayland, it can be spotted in other apps using certain versions.

**Comment by Naadiyaar** [comment]
Should I report upstream?

**Comment by A6GibKm** [comment]
Why not, but then again they dont really support wayland. This flatpak has a setting to force the use of wayand and thats the real issue.

**Comment by Naadiyaar** [comment]
what electron version is used here?

**Comment by Naadiyaar** [comment]
still present at 1.11.36

**Comment by byquanton** [comment]
@bbhtt It is fixed in Element 1.11.37 with the Dependencies Dump (https://github.com/vector-im/element-desktop/blob/ef457ca9d71513162bcfa3a92fd6bf4243ee64eb/yarn.lock#L3516)

**Comment by bbhtt** [comment]
Element was updated to 1.11.37 last week. Closing, thanks!
