### ISSUE TITLE
No window decorations on Wayland

### ISSUE THREAD

**Issue by benjamin051000** [flathub/im.riot.Riot#389]
When the Element window opens on Fedora 38 (running GNOME 44.3 on Wayland), the window titlebar does not have any close, maximize, or minimize buttons, AKA window decorations.

**Comment by LorbusChris** [comment]
Dupe of https://github.com/flathub/im.riot.Riot/issues/380?

**Comment by byquanton** [comment]
Is your Element uptodate?  It's fixed since 1.11.37
![grafik](https://github.com/flathub/im.riot.Riot/assets/32410361/05915f26-0325-454c-9157-1ab47bc8f875)

**Comment by benjamin051000** [comment]
I think it may have updated in the background because now they are here. Woohoo!
