### ISSUE TITLE
Shader compilation broken

### ISSUE THREAD

**Issue by razzeee** [flathub/im.riot.Riot#411]
After updating mesa element started and basically did not display anything usable.

See https://github.com/microsoft/vscode/issues/190437 for the similar vscode issue

Can be fixed by running 
```
rm -rf ~/.var/app/im.riot.Riot/config/Element/GPUCache
```

**Comment by yajo** [comment]
Thanks for the workaround! Element works fine after removing that file.

**Comment by mejo-** [comment]
In my case it was `~/.var/app/im.riot.Riot/config/Riot/GPUCache`, but indeed removing that fixed latest Element for me :innocent:

**Comment by zestygrass** [comment]
Same issue here, the fix works, Thank you

**Comment by razerrazer** [comment]
even if i remove that folder, the issue exist.

**Comment by razzeee** [comment]
You need to restart the app

**Comment by SISheogorath** [comment]
Would it make sense to drip the shader cache on startup of Element for now? It is supposed to be fixed in Chrome by now, but it'll take some time to "trickle down".

**Comment by razzeee** [comment]
Not sure, it might cause slowness, sucks either way.

At least this MS person thinks it's no a good idea (but we're acting with a different slice of the userbase)
https://github.com/microsoft/vscode/issues/190437#issuecomment-1682287495

**Comment by razzeee** [comment]
As far as I understand, this should be fixed now. At least in the case of element.

Other electron apps might need to update their dependency. Vscode has also been fixed.
