### ISSUE TITLE
UI Non-functional on Fedora 38 Wayland

### ISSUE THREAD

**Issue by Codysseus** [flathub/im.riot.Riot#413]
![image](https://github.com/flathub/im.riot.Riot/assets/9455568/69680764-49e1-497d-8701-4de623f3e670)
Upon opening Element, I am greeted with this. Some text boxes are interactive, and I can click on buttons, but absolutely no text shows up. 
This does however work on X11.

Fedora 38
version 1.11.48

**Comment by Codysseus** [comment]
Could not reproduce. Issue likely fixed by logging out.

**Comment by zner0L** [comment]
This issue is a duplicate of #411. You should also delete the mesa shader cache: `rm -rf .var/app/im.riot.Riot/cache/mesa_shader_cache` and then kill the running element using: `flatpak kill im.riot.Riot`
