### ISSUE TITLE
"Start automatically at system login" does not work

### ISSUE THREAD

**Issue by biswasab** [flathub/im.riot.Riot#44]
"Start Automatically on system login" doesn't seem to work. 
![Screenshot from 2019-04-27 20-16-59](https://user-images.githubusercontent.com/17230826/56851160-98d23780-6929-11e9-960c-43b417dc5747.png)

**Comment by SISheogorath** [comment]
I'm not really sure we want to fix that. Start on login and similar functionalities should be manged by the Desktop Environment, not applications within flatpak. But I'm open for ideas here, maybe it's just a permission we need to add.

**Comment by biswasab** [comment]
@SISheogorath My primary guess is a missing permission. Let's see. 
BTW, I am on Fedora 29 with gnome desktop.

**Comment by SISheogorath** [comment]
Here we go: https://github.com/flatpak/flatpak/issues/118

The answer seems to be: Ignore those buttons within flatpak applications for now and use Gnome Tweaks to setup a desktop file.

**Comment by biswasab** [comment]
@SISheogorath , Hmm. Do you know the command to start riot hidden? On geary, I use `--hidden`.

**Comment by SISheogorath** [comment]
@biswasab yes, it should also be `--hidden` according to the library that Riot uses for this feature.

`flatpak run im.riot.Riot --hidden` seems to work in console.

**Comment by biswasab** [comment]
@SISheogorath Cool thanks.
