### ISSUE TITLE
Element always runs into erros with stored credentials after reboot

### ISSUE THREAD

**Issue by solomoncyj** [flathub/im.riot.Riot#465]
### Steps to reproduce

1. log in to element
2. reboot system
3. relaunch element
4. element stuck starting and i need to relaunch and will sign me out after relaunch/ Unable to restore session page

#### What did you expect?
element starting normaly

#### What happened instead?
element stuck starting and i need to relaunch and will sign me out after relaunch/ Unable to restore sessionr page

### Operating system

Fedora 40 KDE

### Application version

1.11.73

### How did you install the app?

flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SISheogorath** [comment]
Duplicates #481
