### ISSUE TITLE
Not exposing filesystem.

### ISSUE THREAD

**Issue by gegoxaren** [flathub/im.riot.Riot#501]
For some reason it seems that Element no longer can attach files. I'm pretty sure it worked before.

When I try to use the attach file option in the chat window, no files are shown in the file dialogue. 
![Skärmbild från 2024-12-26 14-48-56](https://github.com/user-attachments/assets/358da456-271c-4f04-9b05-02140e0f7311)

It would seem that it does not use the FileChooser Desktop Portal.

**Comment by SISheogorath** [comment]
Duplicate https://github.com/flathub/im.riot.Riot/issues/492#issuecomment-2503508579
