### ISSUE TITLE
MATE: Tray icon only appears after notification

### ISSUE THREAD

**Issue by E-werd** [flathub/im.riot.Riot#52]
On MATE 1.22, and possibly other versions of the DE, the tray icon only shows once there's been a notification in Riot.  Until that happens the program cannot be terminated unless you do it from terminal.

**Comment by heipa0** [comment]
That was an upstream issue and should be fixed with Version 1.23
https://github.com/vector-im/riot-web/pull/10097

**Comment by E-werd** [comment]
Confirmed, issue gone.
