### ISSUE TITLE
Tray icon issue with Ubuntu Appindicators 

### ISSUE THREAD

**Issue by heipa0** [flathub/im.riot.Riot#54]
Hi, under Ubuntu 19.04 the tray icon is not working after starting Riot.

Only after restarting the gnome shell the icon shows up. Then it works without issues.

![riot](https://user-images.githubusercontent.com/35292661/60955077-b1e86300-a332-11e9-856c-f9abce4f06c2.png)

I am not sure if this is a problem with the Ubuntu Appindicators extension or the Riot flatpak, however I tested the tray icon with other flatpaks (skype, telegram) and there I don't have this issue. Also the deb version of Riot works fine.

Any ideas?

**Comment by heipa0** [comment]
I found a solution for this issue. It is a permission problem.

After running the following command  

`sudo flatpak override --talk-name=org.kde.StatusNotifierWatcher im.riot.Riot`

the tray icon works fine under Ubuntu.

Would be great if this could be added to the flatpak.

**Comment by SISheogorath** [comment]
Wait, kde permissions on Gnome?

**Comment by SISheogorath** [comment]
@heipa0 please check if the version created by @flathubbot works for you

**Comment by heipa0** [comment]
@SISheogorath I just tried it. The version from the flathubbot works fine
