### ISSUE TITLE
Upload files not work in 1.4.1 version and older versions

### ISSUE THREAD

**Issue by liberodark** [flathub/im.riot.Riot#68]
Hi,

Have test all versions of riot in flatpak but is not usable have big bug is not possible de upload file.

Best Regards

**Comment by SISheogorath** [comment]
You can upload and download files from your Downloads directory. If you need further access, feel free to use the `flatpak override` to add more filesystem permissions. As stated in the PR, there is work upcoming, that will allow the usage of portals.

So this is not a bug, but an explicit decision to keep the defaults for security tight.
