### ISSUE TITLE
Doesn't launch on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Pointedstick** [flathub/im.riot.Riot#72]
```
flatpak run im.riot.Riot
Gtk-Message: 20:05:05.957: Failed to load module "unity-gtk-module"
Gtk-Message: 20:05:05.957: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:05:05.957: Failed to load module "canberra-gtk-module"
Other instance detected: exiting
```
There isn't another instance running though:
```
ps -e | grep -i riot | wc -l
0
```

**Comment by TingPing** [comment]
Maybe run `strace` to see if its reading an file or something to detect other instances.

**Comment by Pointedstick** [comment]
Hmm, maybe it's actually right. As soon as I launch it with `flatpak run im.riot.Riot`, two processes are spawned, not one:

```
ps -e | grep -i riot
20924 pts/2    00:00:00 riot-web
20926 pts/2    00:00:00 riot-web
```

Then I guess the first one detects the second and bails out.

**Comment by SISheogorath** [comment]
@Pointedstick (or anyone else running OpenSUSE Tumbleweed) does this issue still exist?

**Comment by Pointedstick** [comment]
Nah it fixed itself a month or two ago. Thanks for following up.
