### ISSUE TITLE
1.5.4 system theme recognition isn't working under i3/Adwaita-dark

### ISSUE THREAD

**Issue by Mikaela** [flathub/im.riot.Riot#77]
After updating the flatpak and restarting Riot I was surprised to see a light theme and I was told that it's a new feature that Riot attempts to detect/match system theme and that it can be disabled in settings under general. I was asked to report this and as I am not sure where the issue belongs to, I will report it here just in case.

* Debian Testing
* i3
* Theme set as Adwaita-dark in: lxappearance gtk-chtheme qt4-qtconfig qt5ct

```
└┌(%:~)┌- flatpak list | grep adwaita
Adwaita theme   org.kde.KStyle.Adwaita          5.11    x86_64  system
Adwaita theme   org.kde.KStyle.Adwaita          5.12    x86_64  system
Adwaita theme   org.kde.KStyle.Adwaita          5.13    x86_64  system
```

However apparently I don't have `org.gtk.Gtk3theme.Adwaita-dark` installed, so I will try doing that. As I wrote this far, I am opening this in case someone else hits this issue too.

**Comment by Mikaela** [comment]
Installing `org.gtk.Gtk3theme.Adwaita-dark` and restarting Riot doesn't seem to resolve the issue.

**Comment by Mikaela** [comment]
Dave at `#riot-web:matrix.org` said:

> yeah, we are looking at what we can do - we may end up just blacklisting to ignore the system on certain OSes

* https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$lMtwx82kdMY_nPdXMAbbc0GoHxr07ojj2V5R8YrP1Wg?via=matrix.org&via=privacytools.io&via=feneas.org

And judging by the above mention ( https://github.com/vector-im/riot-web/issues/11509 ) this may not be Flatpak issue (sorry if it's not).

**Comment by SISheogorath** [comment]
As this shouldn't be a Riot-flatpak specific bug, I'll close this for now. If the upstream issue is resolved and the issue remains, feel more than free to reopen it :)
