### ISSUE TITLE
Everything is extremely slow (maybe just on Wayland)

### ISSUE THREAD

**Issue by ArchieT** [flathub/im.riot.Riot#8]
For some reason everything is super slow, typing is slow, UI is slow, scrolling is slow, incoming messages, everything. Fedora 25, Gnome (Wayland). Slack works fine, from Flathub: Discord, Telegram work just fine as well. I have 800MiB of RAM free and 2.3GiB available out of 16GB (15GiB) right now. Had this for a while now, I think even when I had more than 3GB free. CPU is pretty much idling all the time. Will do attempt to reproduce with less load and possibly on different systems later.

**Comment by TingPing** [comment]
>  Fedora 25, Gnome (Wayland)

That is extremely old in Wayland time, 2 major releases have made a lot of progress and polish.

Anyway this doesn't have wayland access and it has all the expected x11 access so the blame is either in xwayland or the app and nothing can be done about that here.
